### ISSUE TITLE
Not working in Firefox 36.0.1

### ISSUE THREAD

**Issue by manuti** [chitsaou/copy-as-markdown#24]
It works just the last update. Firefox 36.0.1 on Ubuntu amd64 14.04LTS

**Comment by chitsaou** [comment]
Thanks for reporting. Will take a look.

**Comment by chitsaou** [comment]
I'm in Firefox 37 Beta and everything works. Could you describe more?

**Comment by manuti** [comment]
Is possible to enable some debug mode? How I can help you?
The add-on appears to be enable but not showing in the upper bar or by right clicking-

**Comment by chitsaou** [comment]
I have no idea about debug mode, but you can try uninstall and reinstall the add-on. If still not working, you can try it on another computer.

**Comment by manuti** [comment]
Upadated to Firefox 37 under ubuntu 14.04LTS 64 bits and continued not working. Any chance to resolve?
![captura de pantalla de 2015-05-04 22 52 30](https://cloud.githubusercontent.com/assets/1991606/7462234/48e29754-f2b0-11e4-9bdf-1c4881894afe.png)

**Comment by chitsaou** [comment]
I have no problem on the same environment. Would it be incompatibility with other addons? Could you retry with a new Firefox profile?

![firefox](https://cloud.githubusercontent.com/assets/10737/7492735/a9363d1c-f42d-11e4-9fef-f7725f568c8f.png)

**Comment by manuti** [comment]
OK, I try, thanks.

**Comment by manuti** [comment]
Finally it works again, I didn’t do anything but now works.
Thanks.
