### ISSUE TITLE
Keyboard shortcut(s)

### ISSUE THREAD

**Issue by kenny-evitt** [chitsaou/copy-as-markdown#25]
*Current Tab* in particular would be great. *All Tabs (n)* would be great too.

**Comment by kenny-evitt** [comment]
My bad! I didn't read the *README*.

**Comment by chitsaou** [comment]
This make me think about how I can improve the UI for keyboard shortcuts :)

**Comment by kenny-evitt** [comment]
@chitsaou you're welcome! Thanks for the great extension by the way.
