### ISSUE TITLE
Is there any way to copy multi links at the same time ?

### ISSUE THREAD

**Issue by aneasystone** [chitsaou/copy-as-markdown#26]
Thanks for this brilliant extension, it saves me a lot of time.

But I usually need to copy multi links at the same time, for example, I want to copy this project's title.

<a href="/chitsaou">chitsaou</a> / <a href="/chitsaou/copy-as-markdown">copy-as-markdown</a>

The html code is like this:
```
<a href="/chitsaou">chitsaou</a> / <a href="/chitsaou/copy-as-markdown">copy-as-markdown</a>
```

Is it possible to copy this as:

```
[chitsaou](https://github.com/chitsaou) / [copy-as-markdown](https://github.com/chitsaou/copy-as-markdown)
```

Go a step further, is there any way to copy selected block to markdown directly?

Sincerely.

**Comment by chitsaou** [comment]
Sorry, but this is currently not possible according to the browser's API functions.

By doing this we're going to make it "copy any HTML as markdown" which is a much complex problem :p

**Comment by aneasystone** [comment]
I have found some useful chrome extensions worked the way just like I said.

For example, [View Selection Source](https://chrome.google.com/webstore/detail/view-selection-source/fbhgckgfljgjkkfngcoeajbgndkeoaaj), this extension can be used to view selection HTML source.  

And a little tip from the [source code here](https://github.com/kurrik/chrome-extensions/blob/master/contentscript-selection/contentscript.js), it can get the selection HTML from the `commonAncestorContainer` property of a range object.

```
var selection = window.getSelection();
var range = selection.getRangeAt(0);
var container = range.commonAncestorContainer;

var payload = {
  'text': selection.toString(),
  'html': container.innerHTML
};

chrome.extension.sendRequest(payload); 
```

Then, use [markdown-js](https://github.com/evilstreak/markdown-js) to convert HTML to markdown.

I'll take a deep look into this for more details.

And again, thanks any way.
