### ISSUE TITLE
copying links/page titles with embedded '[' or ']'

### ISSUE THREAD

**Issue by wilx** [chitsaou/copy-as-markdown#31]
Copying the title of <https://www.youtube.com/watch?v=SNE2oCZH_4k> page results into string like this:

~~~~
[M.O.O.N. - 'Hydrogen' [Hotline Miami Soundtrack] - YouTube](https://www.youtube.com/watch?v=SNE2oCZH_4k)
~~~~

Notice the unescaped angle brackets. Pasting that to, e.g., stackoverflow.com chat results into a broken link/Markdown. The angle brackets should be escaped by backslash.

**Comment by wilx** [comment]
Looking at [Pandoc source](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/Markdown.hs#L254), these should be escaped: 

~~~~
\`*_[]#
~~~~

**Comment by chitsaou** [comment]
@wilx Thanks for reporting. I have fixed this bug and released both Chrome and Firefox versions on the corresponding stores. Please check :)

**Comment by chitsaou** [comment]
@wilx Some users (including me, to be honest) don't like this feature because in most cases, Markdown processors handle such cases with no problem.

My goal is to make escaping work fine only when it is necessary.

Do you have any ideas?

**Comment by chitsaou** [comment]
Note: See #34 for more details

**Comment by wilx** [comment]
@chitsaou I replied there.
