### ISSUE TITLE
Escape characters are being included in titles

### ISSUE THREAD

**Issue by patkujawa-wf** [chitsaou/copy-as-markdown#34]
I think this is new with Version: 1.1.0, Updated: January 11, 2016. When you use it on a page with underscores or brackets (probably other chars), the backslash appears in the title when it shouldn't, e.g. a page with the title `[a_b]` is being copied as `[\[a\_b\]](http://example.com)`

**Comment by patkujawa-wf** [comment]
Hmmm, not for all pages, though. For instance, https://en.wikipedia.org/wiki/Glob_%28programming%29 is copied as `[glob (programming) - Wikipedia, the free encyclopedia](https://en.wikipedia.org/wiki/Glob_%28programming%29)`, which is ok...

**Comment by patkujawa-wf** [comment]
For example, JIRA urls often have brackets:
https://jira.atlassian.com/browse/BON-42457 gets copied as `[\[BON-42457\] The button is not working - Atlassian JIRA](https://jira.atlassian.com/browse/BON-42457)`

**Comment by patkujawa-wf** [comment]
I'm guessing [fix the bug that link title is not escaped by chitsaou · Pull Request #32 · chitsaou/copy-as-markdown](https://github.com/chitsaou/copy-as-markdown/pull/32) caused this change

**Comment by patkujawa-wf** [comment]
Ah, so that was intentional. Bummer. Github always seemed to be ok with brackets and underscores, even if stackoverflow wasn't. Can you make this a setting that we can disable? Typically, I use this extension just to get the page title so the link makes sense when I paste it in hipchat or other non-markdown textboxes, so it isn't only useful for markdown :)

**Comment by patkujawa-wf** [comment]
Also, http://daringfireball.net/projects/markdown/dingus handles unescaped stuff just fine, e.g. `[[_]](http://daringfireball.net/projects/markdown/dingus)`

**Comment by chitsaou** [comment]
Thanks for your suggestion.

You're right, most Markdown processors handle this with no problem. I understand that it could be a little bit annoying when there is no escape problem in the text, and in most cases, the text should be fine.

The only case I found so far is incomplete bracket like `[[test](http://example.com)`, which mostly don't happen.

I will think about the need of this feature and put my thoughts here.

**Comment by chitsaou** [comment]
The only case that mentioned in #31 is on https://chat.stackoverflow.com

![screen shot 2016-01-14 at 14 31 12](https://cloud.githubusercontent.com/assets/10737/12317360/8faf326c-bacb-11e5-918a-75dddf99b8b6.png)

IMHO this doesn't make it necessary to escape all the unescaped chars.

**Comment by wilx** [comment]
I think this is not solvable with one solution working for all. Maybe an option to turn escaping on/off and keeping the default as off would work for most?

**Comment by chitsaou** [comment]
Sorry for late response. I will add an option for this.

**Comment by chitsaou** [comment]
Hey, I have made it an option. It is now disabled by default.

It may take some time for Chrome / Firefox web stores to distribute new versions worldwide, but should not be too long.

For Chrome: Go to "Extensions" page, find "Copy as Markdown" and click "options" to enable it.

For Firefox: Go to "Add Ons" page, find "Copy as Markdown" and click "Preferences".

Feel free to give me any suggestions :)

**Comment by wilx** [comment]
Cool! :+1:

**Comment by patkujawa-wf** [comment]
Nice! Thanks, I really appreciate it :)
![image](https://cloud.githubusercontent.com/assets/6391742/12590536/b45a535e-c420-11e5-99a2-aee812856265.png)
