### ISSUE TITLE
[Firefox] Not available in private windows

### ISSUE THREAD

**Issue by KillianKemps** [chitsaou/copy-as-markdown#39]
Hello,

Thanks for your plugin which helps to spend less time when writing in Markdown. I tried it and it works well with normal windows.

However, I often use the private windows in Firefox and the "Copy as markdown" action doesn't show on right click.  It appears only in normal windows.

Could you make your plugin also available in private windows?

I'm using Firefox 47.0.1 on Linux.

**Comment by chitsaou** [comment]
Thanks for your report. Confirm this issue.

I'll take a look.

Probably this option: https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/private-browsing#Opting_into_private_browsing

**Comment by chitsaou** [comment]
Hi, 

Sorry for being so late.

I'm developing a new version for Firefox 57 Nightly, and found that the new version also works in Private Window on Firefox 54. If you'd like to try it out, please head to https://addons.mozilla.org/en-US/firefox/addon/copy-as-markdown/ and scroll down to Development channel to install 2.0.0rc1.

Please kindly let me know if you encounter any issue in Private Browser.

Cheers 🍻

**Comment by chitsaou** [comment]
Hi, 

I just released the new version 2.1.0 that works on Firefox 55 and later.

This version is also confirmed to work in Private Browsing.

I'll close this window now. Please let me know if you got further issues.

Thanks!

**Comment by KillianKemps** [comment]
Thank you! I can confirm that it works in Private Browsing.
