### ISSUE TITLE
Not compatible with multiprocess (Firefox)

### ISSUE THREAD

**Issue by QuAzI** [chitsaou/copy-as-markdown#43]
Add-on Compatibility Reporter say than multiprocess can't be enabled because some extenstion doesn't support it.
![_ _-_vimperator_firefox_2016-12-01_11-10-49_ejkwlioe](https://cloud.githubusercontent.com/assets/1897605/20786407/f29fb520-b7b6-11e6-9207-862643d28112.png)

**Comment by chitsaou** [comment]
Thanks! Will take a look

**Comment by chitsaou** [comment]
Hi @QuAzI, I have released a beta version 1.3.0rc1 on Firefox Add-ons here:

https://addons.mozilla.org/en-US/firefox/addon/copy-as-markdown/versions/beta

Would you help me try it out and let me know if it works for multiprocess Firefox? (I've tried on Firefox Developer Edition, though)

Thanks!

**Comment by sebastienbarre** [comment]
@chitsaou Beta version works great, thanks very much.

**Comment by chitsaou** [comment]
Submitted to Firefox add-ons. Stay tuned!
