### ISSUE TITLE
Keyboard shortcuts (other than activating extension) don't work (OSX at least)

### ISSUE THREAD

**Issue by patkujawa-wf** [chitsaou/copy-as-markdown#49]
Used to work. Upgraded today and now they don't. ~~Clicking the buttons themselves still works.~~ I was wrong, the buttons don't work either :/

EDIT: It seems that the buttons work until you set up a keyboard shortcut and try to use it, then the keyboard shortcut does nothing and the buttons also cease to do anything. Uninstalling and reinstalling the extension gets you back to square one, but adding shortcuts again causes it to get stuck.

**Comment by patkujawa-wf** [comment]
Can you point me to the CRX of the previous version, for now? Keyboard shortcuts are basically the only way I use this extension, and now I'm feeling a lot of pain :(

**Comment by chitsaou** [comment]
Sorry for trouble. Can you check the version and see if it is 2.0.0rc2? 

If so, then I might made some mistake on Chrome web store.

It is supposed to be a private beta version that I'll check today, but unexpectedly shipped to general users.

I'll try to revert to the previous version on Chrome Web Store.

**Comment by chitsaou** [comment]
Sorry it seems that I can't revert :/

I'll try to fix this today.

**Comment by chitsaou** [comment]
I just pushed the older version to Chrome Web Store. It's now 2.0.1 with version name 2.0.0rc3 (sounds strange but just a workaround, thanks to poor versioning support on Chrome Web Store)

It should be available in 1 hour. Let me know if you still have issue.

Thanks!

**Comment by patkujawa-wf** [comment]
Thanks, back to working!
![image](https://user-images.githubusercontent.com/6391742/29931239-e0ab8d32-8e2d-11e7-9dc4-c7dbb76a8e50.png)

**Comment by chitsaou** [comment]
Thanks! Will fix the bugs and let you know :)
