### ISSUE TITLE
Does not copy to clipboard in reader mode (FF Quantum)

### ISSUE THREAD

**Issue by jhermann** [chitsaou/copy-as-markdown#53]
In FF Quantum (FF 57.0), when I entered reader mode for a page, the menu items are there, but don't actually change the clipboard.

**Comment by chitsaou** [comment]
Thanks for report. Interesting. Not sure if I should report this to Firefox bugzilla or not, but I'll take a look.

**Comment by chitsaou** [comment]
I checked with Firefox 60, and the menu item is now missing. 

I noticed (from developer tool) that Firefox Reader View is using `about:reader` scheme, which is not allowed as a permission for a Firefox add-on.

That being said, it is not possible to load add-ons in Reader View.
