### ISSUE TITLE
Copy link doesn't fetch title

### ISSUE THREAD

**Issue by azzamsa** [chitsaou/copy-as-markdown#56]
I am happy user of [copy-as-org-mode](https://github.com/kuanyui/copy-as-org-mode). But since I can't use it in Quantum. I use copy-as-markdown to my org-mode buffer than invoke [my function](https://github.com/azzamsa/emacs.d/blob/master/myelisp/make-md-to-org.el) to transform the link to org-mode.

**But**, I can have title.
 When I use copy-as-org-mode, I often copy link in SO questions ( I can have the title, even I copy the link of the question) . But with copy-as-markdown, I get `no-title`.

e.g 

When I copied this link
![2018-02-26-19 20 16](https://user-images.githubusercontent.com/17734314/36670477-15b0fb18-1b2b-11e8-92a8-af8463bfd0e3.png)

I get 

```
[(No Title)](https://emacs.stackexchange.com/questions/33380/cant-set-default-servers-in-erc-layer)
```

Expected output

```
[Can't set default servers in ERC layer](https://emacs.stackexchange.com/questions/33380/cant-set-default-servers-in-erc-layer)
```

Firefox 58.0.2
Debian 9.2

**Comment by chitsaou** [comment]
Thanks. This is a known issue, and there is a patch #55 that tries to fix it. I'll let you know when it is fixed.

**Comment by azzamsa** [comment]
> that tries to fix it

Thank you so much for your contribution to community. :)

**Comment by chitsaou** [comment]
Closing because there is another issue tracking this: #45
