### ISSUE TITLE
Dropdown menu is all black with a dark KDE/Firefox theme

### ISSUE THREAD

**Issue by kleinbottle** [chitsaou/copy-as-markdown#58]
## Summary

The dropdown menu is all black and illegible when used with a KDFE/Firefox dark theme.
## Reproduction Steps

1.
-

## Expected Behavior

- Dropdown box has visible text.

## Actual Behavior

- Dropdown box has invisible text because background and foreground are both black.

## Reproducible Environment

- Browser (Version): Firefox 59.0.2
- Operating System (Version): Linux kernel 4.14.31-1-MANJARO
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=17.1.7
DISTRIB_CODENAME=Hakoila
DISTRIB_DESCRIPTION="Manjaro Linux"
- System Language: English en_IN
- Example Webpage (if applicable): see attached screenshot below.

**Comment by chitsaou** [comment]
I don't have the environment you have. Could you attach a screenshot?

**Comment by kleinbottle** [comment]
I was unable to directly capture the screenshot because the dropdown box disappeared on the next click after what made it appear.

Instead, here is a screenshot taken on my mobile phone that shows what I see.
![black-box](https://user-images.githubusercontent.com/193362/38464186-cb50c53c-3b26-11e8-89d7-1b24ec8482ee.jpg)

Do let me know if you need any further input.

Thanks.

**Comment by chitsaou** [comment]
Thanks. Could you provide the link to that theme? Or is it a built-in theme?

**Comment by kleinbottle** [comment]
It is built-in theme called "Dark" by Mozilla.
![dark-by-mozilla](https://user-images.githubusercontent.com/193362/38469103-2048d7c8-3b6d-11e8-9691-85a3f68cd7b4.png)

**Comment by chitsaou** [comment]
This extension uses Firefox's built-in CSS for the browser action popup page. If it doesn't work well on your desktop environment, please check https://bugzilla.mozilla.org/ and file a ticket on Firefox project.
