### ISSUE TITLE
Direct context menu if there's only one option

### ISSUE THREAD

**Issue by borekb** [chitsaou/copy-as-markdown#59]
What an awesome extension! I use it via a context menu and this is what I see 99% of the time as I'm generally interested only in full page titles:

![image](https://user-images.githubusercontent.com/101152/38862107-5fff62ba-4234-11e8-8747-185448154894.png)

This means that I need to hover over the top-level menu item, move my cursor to the right and select the single option. Would it be possible to somehow make the top-level item do the copy already if there's just a single nested item?

I realize that there are situations where there are more nested items, in which case they would stay. For example:

![image](https://user-images.githubusercontent.com/101152/38862229-aeb23374-4234-11e8-8a9c-39330bd0b191.png)

**Comment by chitsaou** [comment]
Hi, thanks for your suggestion. It turns out that the default behavior in Chrome and Firefox are exactly what you wished, so I modified it with just a little bit code modifications.

The new version is now available on Chrome Web Store and Firefox Add-Ons. 

Enjoy!

**Comment by borekb** [comment]
Awesome, thank you!
