### ISSUE TITLE
feature request: using shortlinks

### ISSUE THREAD

**Issue by geminorum** [chitsaou/copy-as-markdown#60]
support for [short-link](http://microformats.org/wiki/rel-shortlink) on the `head`:
```
<link rel='shortlink' href='...' />
```

**Comment by chitsaou** [comment]
Thanks for your idea. I did a quick research, and found no practical usage of this attribute. I mean, it might be useful, but doesn't seem to be used on many websites. If you have more example, please post here. Thanks.
