### ISSUE TITLE
usage: what means about option "Escape Markdown code"

### ISSUE THREAD

**Issue by tmc9031** [chitsaou/copy-as-markdown#62]
![image](https://user-images.githubusercontent.com/6755874/40826481-4f98c640-65ad-11e8-94e4-a230a5aae9a7.png)

**Comment by tmc9031** [comment]
@chitsaou i don't know the icon usage

**Comment by mootari** [comment]
From the [Firefox Jetpack description](https://github.com/chitsaou/copy-as-markdown/blob/7c764a9deef190d48763a245370851a4c8c5dbd2/firefox-jetpack/package.json#L13):
> If checked, all unsafe Markdown code will be escaped (e.g. [] becomes \\[\\])

This option was introduced in #34 to handle characters in titles that are recognized by markdown.

**Comment by chitsaou** [comment]
This option has bene introduced by #34 and to be honest I don't think it should be an optional feature anymore. Let me think how to redesign this feature. Thanks for your input.
