### ISSUE TITLE
Copy as Markdown not copying from addons.mozilla.org (AMO)

### ISSUE THREAD

**Issue by grahamperrin** [chitsaou/copy-as-markdown#63]
I recall that when AMO tightened its CSP a few months ago, a variety of extensions became non-applicable to AMO – [washing machine](https://addons.mozilla.org/addon/washingmachine/), for example: 

- https://addons-dev.allizom.org/addon/tab-scope/ (dev) can be spun in the machine
- https://addons.mozilla.org/addon/tab-scope/ can not.

Today I was surprised by Copy as Markdown (and [Link Text and Location Copier](https://addons.mozilla.org/addon/link-text-and-location-copier/)) not working at AMO. Surprised because I'm an extremely frequent user of Copy as Markdown, and I must have copied titles and URLs from AMO pages on hundreds or thousands of occasions in recent months, and I don't recall performing the copies without Copy as Markdown. 

Am I going mad? (Has the extension _never_ worked with the the increased CSP at AMO?)

I'm aware of WebExtensions APIs and so on, just surprised by the non-function _today_.

----

Using Waterfox, if that's relevant. Recently updated to 56.2.0.31 on FreeBSD-CURRENT.

**Comment by chitsaou** [comment]
I don't use Firefox daily, but I barely remember that, when I was testing on AMO, it doesn't work at all. I believe it's intentionally blocked by Firefox, so the AMO site won't be replaced by a malicious add-on.

It'd be great if you could find the related resource describing this fact. If not, maybe I am wrong :)

**Comment by grahamperrin** [comment]
The same behaviour with Firefox 65.0. 

Is it possible to suppress (or grey-out) the menu item in domains where it can't be used? 

I mean, I know to not expect functionality at AMO but the _apparent_ silent failure to copy might take other users by surprise. 

TIA
