### ISSUE TITLE
Asking for "Read your browsing history" permission again!?

### ISSUE THREAD

**Issue by ruifortes** [chitsaou/copy-as-markdown#70]
It looks like issue #50 has returned. What gives?

**Comment by chitsaou** [comment]
That's wired. This extension doesn't include any permission about browser history https://github.com/chitsaou/copy-as-markdown/blob/master/src/manifest.chrome.json#L8-L11

**Comment by chitsaou** [comment]
Sorry, I checked Chrome again and see it has "Read your browsing history". I suppose there is some misleading UI in Chrome.

Disclaimer: I've been not using Chrome for a very long time.

**Comment by chitsaou** [comment]
Ok, here is why:

https://developer.chrome.com/extensions/permission_warnings#view_warnings

> Permission warnings exist to describe the capabilities granted by an API to extension users, but some of these warnings may not be obvious at first. **For instance, adding the "tabs" permission results in a seemingly unrelated warning: the extension can Read your browsing activity.** Although the chrome.tabs API might be used to only open new tabs, it can also be used to see the URL that is associated with every newly opened tab by using their tabs.Tab objects.

So yes, logically using `tabs` permission can "Read your browsing history" in some ways. This extensions doesn't store and share any of your browsing history. The only place that `tabs` is being used is when you click "All Tabs" in the drop down menu of "md" button in browser toolbar.

**Comment by ruifortes** [comment]
Ahhh!! Of course, that makes sense. Great extension then :)
Thanks
