### ISSUE TITLE
Right-click context menu not available in Chrome

### ISSUE THREAD

**Issue by myitcv** [chitsaou/copy-as-markdown#72]
This is a follow up to https://github.com/chitsaou/copy-as-markdown/issues/65#issuecomment-541533366 because I couldn't re-open that issue.

## Summary

Per https://github.com/chitsaou/copy-as-markdown/issues/65

## Reproduction Steps

Per https://github.com/chitsaou/copy-as-markdown/issues/65

## Expected Behavior

Per https://github.com/chitsaou/copy-as-markdown/issues/65

## Actual Behavior

Per https://github.com/chitsaou/copy-as-markdown/issues/65

## Reproducible Environment

- Browser (Version): Google Chrome Version 78.0.3904.50 (Official Build) beta (64-bit)
- Operating System (Version): macOS 10.12.6
- System Language: English
- Example Webpage (if applicable): n/a

**Comment by myitcv** [comment]
Closing per https://github.com/chitsaou/copy-as-markdown/issues/65#issuecomment-541545636

**Comment by chitsaou** [comment]
As mentioned in #65, there is no such feature (yet).

The closest feature would be "convert a selected text to Markdown", which would be #29.

Thanks for your suggestions.
