### ISSUE TITLE
Extension no longer working after recent update in chrome 77

### ISSUE THREAD

**Issue by mohanraj-r** [chitsaou/copy-as-markdown#74]
## Summary

After the recent update, during which I had to re-enable the extension due to elevated permissions, it no longer works in chrome. Both clicking on the extension directly and using the shortcut key does not work. I see no output/error in dev console. Also tried disabling, re-enabling and reloading the page - nothing helps.

## Reproducible Environment

- Browser (Version): Chrome 77
- Operating System (Version): Mac OS 10.14
- System Language: English, en_US

**Comment by chitsaou** [comment]
Hi, there is a bug in 2.4.0 that may cause this issue. Could you try with 2.4.1 which has been updated yesterday?

**Comment by chitsaou** [comment]
Hi, I found another bug related to the issue you reported. Could you try 2.4.2 ?

**Comment by mohanraj-r** [comment]
Thanks @chitsaou Looks like its working now!

**Comment by chitsaou** [comment]
Thanks. Let me close this issue :)
