### ISSUE TITLE
New user, right click copy to markdown missing

### ISSUE THREAD

**Issue by datocrats-org** [chitsaou/copy-as-markdown#77]
## Summary

I am attempting to right click to copy as markdown from website that clearly uses markdown-compatible text: https://www.holunda.io/camunda-bpm-feign/wiki/introduction/features/

## Reproduction Steps

1. Right click

## Expected Behavior
1. Right click
2. copy as markdown

## Actual Behavior
1. Right click
2. no such option to copy as markdown

## Reproducible Environment

- Browser (Version): Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)
- Operating System (Version): Windows 10
- System Language: en_US
- Example Webpage (if applicable): https://www.holunda.io/camunda-bpm-feign/wiki/introduction/features/

**Comment by chitsaou** [comment]
Hi, this extension does not help you convert a webpage to Markdown yet (aka. "scrape a webpage as Markdown"). There are a few feature requests about this, but at this moment, this extension is focused on time consuming things such as "export tabs as a list of Markdown".
