### ISSUE TITLE
Stopped working with Firefox 60.9.0esr (Debian Stretch)

### ISSUE THREAD

**Issue by silbe** [chitsaou/copy-as-markdown#78]
## Summary

When I tried to use the `Copy [Link Content](URL)` context menu item today, it didn't do anything. My guess is that it's related to the changes from #71 (Firefox automatically updated the add-on to 2.4.3 yesterday).

## Reproduction Steps

1. Right-click on a link to open the context menu. Select the `Copy [Link Content](URL)` context menu item .

## Expected Behavior

- Copy link as markdown to clipboard

## Actual Behavior

- Clipboard is unchanged

## Reproducible Environment

- Browser (Version): Firefox 60.9.0esr (60.9.0esr-1~deb9u1)
- Operating System (Version): Debian Stretch amd64
- System Language: en_GB

**Comment by chitsaou** [comment]
Hi, Firefox 60 is not the latest version and is not supported.

The latest ESR version 68 is 2 versions behind the active version today (70), so it's unlikely supported.

Please update your browser and try again.
