### ISSUE TITLE
Convert selected HTML elements to markdown

### ISSUE THREAD

**Issue by anishmittal2020** [chitsaou/copy-as-markdown#79]
# Goal

To select any HTML element on a page and convert it to markdown

# Purpose of this functionality

Useful to make notes from websites.

# Available tools (and its limitations)

[JohnnyFee/CopyAsMarkdown: This is a Chrome Extension used to copy the element in current page as markdown format.](https://github.com/JohnnyFee/CopyAsMarkdown), does what I am requesting, but the tool is no longer supported and has several npm vulnerabilities and is not available in firefox.

# Example

When I copy and press `Alt` + `c` (to activate the extension) on the website: [Navier–Stokes equations - Wikipedia](https://en.wikipedia.org/wiki/Navier%E2%80%93Stokes_equations)

![image](https://user-images.githubusercontent.com/42092626/67421519-f4c40300-f5d0-11e9-95f8-9f43ed62147c.png)

I get the following when I paste it in my editor:

```markdown
These balance equations arise from applying [Isaac Newton's second law](https://en.wikipedia.org/wiki/Newton%27s_second_law "Newton's second law") to [fluid motion](https://en.wikipedia.org/wiki/Fluid_dynamics "Fluid dynamics"), together with the assumption that the [stress](https://en.wikipedia.org/wiki/Stress_(mechanics) "Stress (mechanics)") in the fluid is the sum of a [diffusing](https://en.wikipedia.org/wiki/Diffusion "Diffusion") [viscous](https://en.wikipedia.org/wiki/Viscosity "Viscosity") term (proportional to the [gradient](https://en.wikipedia.org/wiki/Gradient "Gradient") of velocity) and a [pressure](https://en.wikipedia.org/wiki/Pressure "Pressure") term—hence describing *viscous flow*. The main difference between them and the simpler [Euler equations](https://en.wikipedia.org/wiki/Euler_equations_(fluid_dynamics) "Euler equations (fluid dynamics)") for [inviscid flow](https://en.wikipedia.org/wiki/Inviscid_flow "Inviscid flow") is that Navier–Stokes equations also factor in the [Froude limit](https://en.wikipedia.org/wiki/Froude_number "Froude number") (no external field) and are not [conservation equations](https://en.wikipedia.org/wiki/Conservation_law "Conservation law"), but rather a [dissipative system](https://en.wikipedia.org/wiki/Dissipative_system "Dissipative system"), in the sense that they cannot be put into the quasilinear [homogeneous](https://en.wikipedia.org/wiki/Homogeneous_polynomial "Homogeneous polynomial") form:

<dl>
    <dd><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle \mathbf {y} _{t}+\mathbf {A} (\mathbf {y} )\mathbf {y} _{x}=0.}">
      <semantics>
        <mrow class="MJX-TeXAtom-ORD">
          <mstyle displaystyle="true" scriptlevel="0">
            <msub>
              <mrow class="MJX-TeXAtom-ORD">
                <mi mathvariant="bold">y</mi>
              </mrow>
              <mrow class="MJX-TeXAtom-ORD">
                <mi>t</mi>
              </mrow>
            </msub>
            <mo>+</mo>
            <mrow class="MJX-TeXAtom-ORD">
              <mi mathvariant="bold">A</mi>
            </mrow>
            <mo stretchy="false">(</mo>
            <mrow class="MJX-TeXAtom-ORD">
              <mi mathvariant="bold">y</mi>
            </mrow>
            <mo stretchy="false">)</mo>
            <msub>
              <mrow class="MJX-TeXAtom-ORD">
                <mi mathvariant="bold">y</mi>
              </mrow>
              <mrow class="MJX-TeXAtom-ORD">
                <mi>x</mi>
              </mrow>
            </msub>
            <mo>=</mo>
            <mn>0.</mn>
          </mstyle>
        </mrow>
        <annotation encoding="application/x-tex">{\displaystyle \mathbf {y} _{t}+\mathbf {A} (\mathbf {y} )\mathbf {y} _{x}=0.}</annotation>
      </semantics>
    </math>![{\displaystyle \mathbf {y} _{t}+\mathbf {A} (\mathbf {y} )\mathbf {y} _{x}=0.}](https://wikimedia.org/api/rest_v1/media/math/render/svg/e61ca3ba503b1cbee749633b181faeaba727b61c)</dd>
</dl>
```

# Request

Please provide this functionality if possible.

**Comment by chitsaou** [comment]
Hi, this is a feature request that's been asked for several times, but I couldn't see the value of it.

Suppose you're writing an article in Markdown, what's the reason you want to import some rich text from a web page and put it in your article? Markdown doesn't support all formats that are available in HTML, so it's unlikely will be parsed correctly.

Secondly, in many Markdown editors you can embed HTML. So all you need to do is extract the HTML from web page and paste it into Markdown. To do so, you can find an add-on that extracts the selected web content to HTML. Of course, you need a Markdown editor that allows you to embed HTML.  Whether the target rendering environment recognizes the HTML is another story. The example you gave generates a bunch of non-standard HTML tag to display mathematical equations, and is unlikely supported in different browsers.

Therefore, I doubt if this feature provides value that worths me to maintain.

If you really want to convert a given web page HTML to Markdown, consider using [turndown](https://github.com/domchristie/turndown) or other command line tools.
